### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Axkaban** [deanarron/tea_cozy#2]
Nice use of [global selectors](https://github.com/deanarron/tea_cozy/blob/master/resources/styles/style.css#L1-L12)
Just be careful when using the `*` selector, it tends to overwrite the values of the same properties in other selectors. You could apply it to body, or if you rather go through the whole file, you can use the `html` selector.

Great work with [flex](https://github.com/deanarron/tea_cozy/blob/master/resources/styles/style.css#L89) and your [media query](https://github.com/deanarron/tea_cozy/blob/master/resources/styles/style.css#L122)!

**Comment by deanarron** [comment]
Thanks!
