### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [deanarron/tea_cozy#3]
Grade: **Met requirements and expectations**

Congratulations on a job well done! Now, if you also want to explore responsive measurements besides percentages to change some of those `px` you can look at this articles:
On [`em` and `rem`](https://css-tricks.com/rem-global-em-local/), and on [`vh` and `vw`](https://css-tricks.com/viewport-sized-typography/). 

Hope you're enjoying your learning and best of luck!

**Comment by deanarron** [comment]
Thanks so much Axel!
